"""
ComfyUI Metadata Extractor
Extracts metadata from PNG images and MP4/video files generated by ComfyUI
"""

from .metadata_extractor import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
